#!/usr/bin/env python3
r"""Emit LaTeX from results/metrics/paper_data.json — the ONLY way numbers enter the paper.

Writes into the paper dir (default docs/eccv_template/ECCV_2026_GazeAgent_qpaper/):
  numbers.tex        — \newcommand for every load-bearing scalar quoted in prose (rounding decided here)
  tab_*.tex          — complete \begin{tabular}..\end{tabular} fragments for every multi-row table
Both main.tex and supp.tex \input these, so a hand-typed number can never disagree with the data
(verify_numbers.py enforces it). Reads paper_data.json ONLY; no recomputation.
"""
import os, sys, json, argparse
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, "results", "metrics", "paper_data.json")
GP, SHARP = "fov-geisler_perry", "fov-sharp"
TOK = {"qwen3.5-35b-a3b": "Qwen", "glm-4.6v-flash": "Glm", "gemma-4-e4b-it": "Gemma"}
KW = {"fov-sharp": "Sharp", "fov-geisler_perry": "GP", "fov-gaussian-k8": "Keight",
      "fov-gaussian-k16": "Ksixteen", "fov-gaussian-k24": "Ktwentyfour", "fov-gaussian-k32": "Kthirtytwo",
      "fov-gaussian-k48": "Kfortyeight", "fov-gaussian-k128": "Konetwentyeight", "fov-crop": "Crop"}
COND_ORDER = ["fov-sharp", "fov-geisler_perry", "fov-gaussian-k8", "fov-gaussian-k16", "fov-gaussian-k24",
              "fov-gaussian-k32", "fov-gaussian-k48", "fov-gaussian-k128", "fov-crop"]
CLABEL = {c: c.replace("fov-", "").replace("gaussian-", "") for c in COND_ORDER}
SIG_KEYS = ["gaze_entropy", "saccade_amp", "refixation", "scanpath_length", "center_bias", "turn_angle", "hull_area"]
SIG_LBL = {"gaze_entropy": "gaze entropy", "saccade_amp": "saccade amp", "refixation": "refixation",
           "scanpath_length": "scanpath len", "center_bias": "center bias", "turn_angle": "turn angle",
           "hull_area": "coverage"}


def f2(x):   # probability / correlation, 2 dp, keep leading zero
    return "---" if x is None or (isinstance(x, float) and x != x) else f"{x:.2f}"
def f3(x):
    return "---" if x is None or (isinstance(x, float) and x != x) else f"{x:.3f}"
def sgn(x):  # signed 2 dp for deltas, drop leading zero (LaTeX math)
    if x is None or (isinstance(x, float) and x != x): return "---"
    s = f"{abs(x):.2f}".lstrip("0"); return ("$+$" if x >= 0 else "$-$") + s
def fnum(x):  # median fixations: integer, or x.5
    if x is None or (isinstance(x, float) and x != x): return "---"
    return f"{x:.0f}" if abs(x - round(x)) < 1e-6 else f"{x:.1f}"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=os.path.join(ROOT, "docs/eccv_template/ECCV_2026_GazeAgent_qpaper"))
    args = ap.parse_args()
    d = json.load(open(DATA))
    os.makedirs(args.out, exist_ok=True)
    slugs = d["_meta"]["slugs"]; H = d["_human"]; M = {s: d[s] for s in slugs}
    mac = ["% AUTO-GENERATED by scripts/emit_paper_tex.py from results/metrics/paper_data.json. DO NOT EDIT.",
           f"% git {d['_meta']['git_commit']}  config {d['_meta']['config_sha256']}  fast={d['_meta']['fast_mode']}"]
    def C(name, val): mac.append(r"\newcommand{\%s}{%s}" % (name, val))

    # ---- human ----
    C("HumanTFPone", f2(H["tfp1"])); C("HumanTFPend", f2(H["tfpend"]))
    C("HumanNumFixTP", fnum(H["numfix"]["TP"])); C("HumanNumFixTA", fnum(H["numfix"]["TA"]))
    C("HumanNumFixTAmax", str(H["numfix"]["TA_max"]))
    C("HumanCeiling", f3(H.get("scanmatch_ceiling"))); C("HumanDprime", f2(H["decision_sdt"]["dprime"]))
    C("NImages", str(d["_meta"]["n_images"]["TP"] + d["_meta"]["n_images"]["TA"]))
    C("NImagesTP", str(d["_meta"]["n_images"]["TP"])); C("NImagesTA", str(d["_meta"]["n_images"]["TA"]))
    C("NSeeds", str(d["_meta"]["n_seeds"]))
    C("PCApcone", f"{round(d['_pca']['explained_variance_ratio'][0]*100)}")
    C("PCApctwo", f"{round(d['_pca']['explained_variance_ratio'][1]*100)}")
    tot_ep = sum(d["_meta"]["n_episodes"].values())
    C("NEpisodes", f"{tot_ep:,}".replace(",", "{,}"))

    # ---- per model ----
    for s in slugs:
        t = TOK[s]; m = M[s]; det = m["detection"]
        C(t + "TPexist", f2(det["tp_acc"])); C(t + "TAexist", f2(det["ta_acc"]))
        C(t + "YesBias", f2(det["yes_bias"]))
        C(t + "Localiz", f2(det["localization_inbox"]) if det["localization_inbox"] is not None else "n/a")
        for cond, kw in (("fov-sharp", "Sharp"), ("fov-geisler_perry", "GP")):
            fi = m["axes"]["finding"][cond]; de = m["axes"]["decision"][cond]; dy = m["axes"]["dynamics"][cond]
            C(t + kw + "TFPone", f2(fi["tfp1"])); C(t + kw + "TFPend", f2(fi["tfpend"]))
            C(t + kw + "NumFixTP", fnum(fi["numfix_tp_med"])); C(t + kw + "NumFixTA", fnum(de["numfix_ta_med"]))
            C(t + kw + "DeclAbs", f2(de["declared_absent"])); C(t + kw + "FalsePresent", f2(de["false_present"]))
            C(t + kw + "Dprime", f2(de["dprime"]))
            C(t + kw + "EntropyD", sgn(dy["signature"]["gaze_entropy"]["delta"]))
            C(t + kw + "SaccD", sgn(dy["signature"]["saccade_amp"]["delta"]))
            C(t + kw + "CenterD", sgn(dy["signature"]["center_bias"]["delta"]))
            if not d["_meta"]["fast_mode"]:
                sim = m["axes"]["similarity"].get(cond, {})
                C(t + kw + "SelfConsist", f2(sim.get("scanmatch_aa")))
                C(t + kw + "ScanmatchAH", f2(sim.get("scanmatch_ah")))
                if "density" in fi: C(t + kw + "DensityCC", f2(fi["density"]["cc"]))
        # a couple of "no-band" anchor numbers (first gist-k where TFP@1 <= human)
        for cond in ["fov-gaussian-k16", "fov-gaussian-k24", "fov-gaussian-k32"]:
            fi = m["axes"]["finding"].get(cond, {})
            if fi:
                C(t + KW[cond] + "TFPone", f2(fi["tfp1"])); C(t + KW[cond] + "TFPend", f2(fi["tfpend"]))
        # mixed-effects numfix CI-includes-zero flag (the Gemma point)
        me = m["mixed_effects"].get("numfix", {}).get("fixed_vs_human", {}).get("geisler_perry")
        if me:
            incl0 = (me["lo"] <= 0 <= me["hi"])
            C(t + "NumFixCIzero", "yes" if incl0 else "no")
            C(t + "NumFixDelta", f"{me['delta']:+.2f}")
    open(os.path.join(args.out, "numbers.tex"), "w").write("\n".join(mac) + "\n")

    # ================= TABLE FRAGMENTS =================
    def write(name, body): open(os.path.join(args.out, name), "w").write(body)

    # ---- tab_outcome: per condition x model, finding+decision+density (main Table) ----
    rows = [r"\textbf{human} & \textbf{%s} & \textbf{%s} & \textbf{%s} & \textbf{%s} & --- & --- \\" %
            (f2(H["tfp1"]), f2(H["tfpend"]), fnum(H["numfix"]["TP"]), fnum(H["numfix"]["TA"]))]
    for c in COND_ORDER:
        def cell(fn, axis, key):
            return " / ".join(fn(M[s]["axes"][axis][c].get(key)) for s in slugs)
        dens = " / ".join((f2(M[s]["axes"]["finding"][c].get("density", {}).get("cc"))
                           if "density" in M[s]["axes"]["finding"][c] else "---") for s in slugs)
        lab = CLABEL[c]; bold = c == "fov-geisler_perry"
        line = "%s & %s & %s & %s & %s & %s & %s \\\\" % (
            (r"\textbf{geisler\_perry}" if bold else lab),
            cell(f2, "finding", "tfp1"), cell(f2, "finding", "tfpend"),
            cell(fnum, "finding", "numfix_tp_med"), cell(fnum, "decision", "numfix_ta_med"),
            cell(f2, "decision", "declared_absent"), dens)
        rows.append(line)
    write("tab_outcome.tex",
          "\\begin{tabular}{lcccccc}\n\\toprule\ncondition & TFP@1 & TFP-end & NFix-TP & NFix-TA & "
          "TA decl.-abs & dens.\\ CC \\\\\n\\midrule\n" + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")

    # ---- tab_decision (supp): existence + d'/criterion + localization ----
    dr = []
    dr.append("human & --- & --- & --- & %s & %s & --- \\\\" %
              (f2(H["decision_sdt"]["dprime"]), f2(H["decision_sdt"]["criterion"])))
    for s in slugs:
        det = M[s]["detection"]; de = M[s]["axes"]["decision"][GP]
        dr.append("%s & %s & %s & %s & %s & %s & %s \\\\" % (
            M[s]["label"], f2(det["tp_acc"]), f2(det["ta_acc"]), f2(det["yes_bias"]),
            f2(de["dprime"]), f2(de["criterion"]),
            (f2(det["localization_inbox"]) if det["localization_inbox"] is not None else "n/a")))
    write("tab_decision.tex",
          "\\begin{tabular}{lcccccc}\n\\toprule\nmodel & TP exist. & TA exist. & yes-bias & "
          "$d'$ (GP) & criterion & localiz.\\ in-box \\\\\n\\midrule\n" + "\n".join(dr) +
          "\n\\bottomrule\n\\end{tabular}\n")

    # ---- tab_gaze (main): GP gaze deltas + self-consistency ----
    gr = ["human$\\leftrightarrow$human ceiling & --- & --- & --- & %s \\\\" % f3(H.get("scanmatch_ceiling"))]
    for s in slugs:
        dy = M[s]["axes"]["dynamics"][GP]["signature"]; sim = M[s]["axes"]["similarity"].get(GP, {})
        def D(k):
            v = dy[k]["delta"]; b = v == v and abs(v) > 0.33
            return (r"\textbf{%s}" % sgn(v)) if b else sgn(v)
        gr.append("%s & %s & %s & %s & %s \\\\" % (
            M[s]["label"], D("gaze_entropy"), D("saccade_amp"), sgn(dy["center_bias"]["delta"]),
            f2(sim.get("scanmatch_aa"))))
    write("tab_gaze.tex",
          "\\begin{tabular}{lcccc}\n\\toprule\n & gaze entropy $\\delta$ & saccade amp $\\delta$ & "
          "center bias $\\delta$ & AA self-consist. \\\\\n\\midrule\n" + "\n".join(gr) +
          "\n\\bottomrule\n\\end{tabular}\n")

    # ---- tab_signature (supp): full model x condition x 7 metrics, bold |d|>0.33 ----
    sr = []
    for s in slugs:
        for i, c in enumerate(COND_ORDER):
            dy = M[s]["axes"]["dynamics"][c]["signature"]
            cells = []
            for k in SIG_KEYS:
                v = dy[k]["delta"]; cell = sgn(v)
                if v == v and abs(v) > 0.33: cell = r"\textbf{%s}" % cell
                cells.append(cell)
            tag = TOK[s][0] + ("m" if s.startswith("gemma") else "")
            sr.append("%s & %s & %s \\\\" % (tag if i == 0 else "", CLABEL[c].replace("_", "\\_"), " & ".join(cells)))
        if s != slugs[-1]: sr.append("\\midrule")
    hdr = " & ".join(SIG_LBL[k] for k in SIG_KEYS)
    write("tab_signature.tex",
          "\\begin{tabular}{ll" + "c" * len(SIG_KEYS) + "}\n\\toprule\nmodel & condition & " + hdr +
          " \\\\\n\\midrule\n" + "\n".join(sr) + "\n\\bottomrule\n\\end{tabular}\n")

    # ---- tab_similarity (supp): AH/AA ScanMatch ladder per model ----
    if not d["_meta"]["fast_mode"]:
        head = " & ".join("\\multicolumn{2}{c}{%s}" % M[s]["label"] for s in slugs)
        sub = " & ".join("AH & AA" for _ in slugs)
        lr = ["\\textbf{human ceiling} & \\multicolumn{%d}{c}{\\textbf{%s}} \\\\" %
              (2 * len(slugs), f3(H.get("scanmatch_ceiling")))]
        for c in COND_ORDER:
            cells = []
            for s in slugs:
                sim = M[s]["axes"]["similarity"].get(c, {})
                cells += [f3(sim.get("scanmatch_ah")), f3(sim.get("scanmatch_aa"))]
            lr.append("%s & %s \\\\" % (CLABEL[c].replace("_", "\\_"), " & ".join(cells)))
        colspec = "l" + "cc" * len(slugs)
        write("tab_similarity.tex",
              "\\begin{tabular}{%s}\n\\toprule\n & %s \\\\\ncondition & %s \\\\\n\\midrule\n%s\n\\bottomrule\n\\end{tabular}\n"
              % (colspec, head, sub, "\n".join(lr)))

    # ---- tab_mixed (supp): mixed-effects 3 models, sharp+GP ----
    mr = []
    nm = {"gaze_entropy": "gaze entropy", "saccade_amp": "saccade amp.", "numfix": "numfix", "tfp1": "TFP@1"}
    for s in slugs:
        for metric in ["gaze_entropy", "saccade_amp", "numfix", "tfp1"]:
            fe = M[s]["mixed_effects"].get(metric, {}).get("fixed_vs_human", {})
            def ci(cond):
                v = fe.get(cond)
                if not v: return "---"
                txt = "$%+.2f$ [$%+.2f,%+.2f$]" % (v["delta"], v["lo"], v["hi"])
                return r"\textbf{%s}" % txt if not (v["lo"] <= 0 <= v["hi"]) else txt
            mr.append("%s & %s & %s & %s \\\\" % (M[s]["label"] if metric == "gaze_entropy" else "",
                                                  nm[metric], ci("sharp"), ci("geisler_perry")))
        if s != slugs[-1]: mr.append("\\midrule")
    write("tab_mixed.tex",
          "\\begin{tabular}{llcc}\n\\toprule\nmodel & metric & sharp $\\Delta$ [95\\% CI] & "
          "geisler\\_perry $\\Delta$ [95\\% CI] \\\\\n\\midrule\n" + "\n".join(mr) +
          "\n\\bottomrule\n\\end{tabular}\n")

    # ---- tab_strata (supp): TFP@1 by stratum, human vs 3 models (sharp) ----
    st_order = ["near-small", "near-large", "far-small", "far-large"]
    rr = []
    for st in st_order:
        h = M[slugs[0]]["strata"][st]["human_tfp1"]; n = M[slugs[0]]["strata"][st]["n"]
        cells = " / ".join(f2(M[s]["strata"][st]["sharp_tfp1"]) for s in slugs)
        rr.append("%s (%d) & %s & %s \\\\" % (st, n, f2(h), cells))
    write("tab_strata.tex",
          "\\begin{tabular}{lcc}\n\\toprule\nstratum (n) & human TFP@1 & sharp TFP@1 (Q / G / Gm) \\\\\n"
          "\\midrule\n" + "\n".join(rr) + "\n\\bottomrule\n\\end{tabular}\n")

    # ---- tab_pca (supp): loadings ----
    pc = d["_pca"]
    def load_str(k):
        items = sorted(pc["loadings"][k].items(), key=lambda kv: -abs(kv[1]))[:3]
        return ", ".join("$%+.2f$ %s" % (v, SIG_LBL.get(f, f)) for f, v in items)
    write("tab_pca.tex",
          "\\begin{tabular}{lcl}\n\\toprule\ncomponent & variance & dominant loadings \\\\\n\\midrule\n"
          "PC1 & %d\\%% & %s \\\\\nPC2 & %d\\%% & %s \\\\\n\\bottomrule\n\\end{tabular}\n" %
          (round(pc["explained_variance_ratio"][0]*100), load_str("PC1"),
           round(pc["explained_variance_ratio"][1]*100), load_str("PC2")))

    # ---- tab_tolerance (supp): max |delta TFP@1| per model ----
    tr = " & ".join(f3(M[s]["tolerance"]["max_shift_tfp1"]) for s in slugs)
    write("tab_tolerance.tex",
          "\\begin{tabular}{lc}\n\\toprule\nmodel & max $|\\Delta$TFP@1$|$ over $\\pm0.5/1/1.5°$ \\\\\n\\midrule\n"
          + "\n".join("%s & %s \\\\" % (M[s]["label"], f3(M[s]["tolerance"]["max_shift_tfp1"])) for s in slugs)
          + "\n\\bottomrule\n\\end{tabular}\n")

    print(f"[emit] numbers.tex ({len([m for m in mac if m.startswith(chr(92)+'newcommand')])} macros) + "
          f"tab_*.tex -> {args.out}")


if __name__ == "__main__":
    main()
